In [6]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import confusion_matrix, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load data from output.csv
data = pd.read_csv('../output/output_binary.csv')

# Split features and labels

feature_df= data.drop(data.columns[:2], axis=1)
X = np.asarray(feature_df)
y=np.asarray(data['pii_exist'])

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Convert labels to one-hot encoding
num_classes = len(np.unique(y))
y_train_one_hot = tf.one_hot(y_train, depth=num_classes).numpy()
y_test_one_hot = tf.one_hot(y_test, depth=num_classes).numpy()

# Define SVM model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_hinge',
              metrics=['accuracy'])

# Define a function for training on each client's data
def train_on_client(X, y, model):
    model.fit(X, y, epochs=10, batch_size=32, verbose=0)
    return model

# Federated learning loop
for _ in range(10):  # 10 rounds of federated learning
    # Client 1 trains on its data
    model = train_on_client(X_train, y_train_one_hot, model)

    # Client 2 trains on its data
    model = train_on_client(X_test, y_test_one_hot, model)

# Predict classes
y_pred = np.argmax(model.predict(X_test), axis=1)

# Calculate confusion matrix and F1 score
conf_matrix = confusion_matrix(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print("Confusion Matrix:")
print(conf_matrix)
print("F1 Score:", f1)


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
Confusion Matrix:
[[262   8]
 [  0  92]]
F1 Score: 0.9781947963832234


In [7]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import confusion_matrix, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load data from output.csv
data = pd.read_csv('../output/output.csv')

# Split features and labels

feature_df= data.drop(data.columns[:2], axis=1)
X = np.asarray(feature_df)
y=np.asarray(data['pii_exist'])

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Convert labels to one-hot encoding
num_classes = len(np.unique(y))
y_train_one_hot = tf.one_hot(y_train, depth=num_classes).numpy()
y_test_one_hot = tf.one_hot(y_test, depth=num_classes).numpy()

# Define SVM model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_hinge',
              metrics=['accuracy'])

# Define a function for training on each client's data
def train_on_client(X, y, model):
    model.fit(X, y, epochs=10, batch_size=32, verbose=0)
    return model

# Federated learning loop
for _ in range(10):  # 10 rounds of federated learning
    # Client 1 trains on its data
    model = train_on_client(X_train, y_train_one_hot, model)

    # Client 2 trains on its data
    model = train_on_client(X_test, y_test_one_hot, model)

# Predict classes
y_pred = np.argmax(model.predict(X_test), axis=1)

# Calculate confusion matrix and F1 score
conf_matrix = confusion_matrix(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print("Confusion Matrix:")
print(conf_matrix)
print("F1 Score:", f1)


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
Confusion Matrix:
[[254   4   5   7]
 [  0  32   0   0]
 [  0   0  56   1]
 [  0   0   0   3]]
F1 Score: 0.9592839266592038


In [12]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import confusion_matrix, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load data from output.csv
data = pd.read_csv('../output/output.csv')

# Split features and labels
feature_df = data.drop(data.columns[:2], axis=1)
X = np.asarray(feature_df)
y = np.asarray(data['pii_exist'])

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Convert labels to one-hot encoding
num_classes = len(np.unique(y))
y_train_one_hot = tf.one_hot(y_train, depth=num_classes).numpy()
y_test_one_hot = tf.one_hot(y_test, depth=num_classes).numpy()

# Define SVM model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_hinge',
              metrics=['accuracy'])

# Define a function for training on each client's data
def train_on_client(X, y, model):
    model.fit(X, y, epochs=10, batch_size=32, verbose=0)
    return model

# Federated learning loop
for _ in range(10):  # 10 rounds of federated learning
    # Simulate 10 clients
    for client_id in range(10):
        # Randomly select train/test split for each client
        X_client_train, X_client_test, y_client_train, y_client_test = train_test_split(X_scaled, y, test_size=0.2, random_state=client_id)
        y_client_train_one_hot = tf.one_hot(y_client_train, depth=num_classes).numpy()
        
        # Train client's local model
        model = train_on_client(X_client_train, y_client_train_one_hot, model)

    # Predict classes on the test set
    y_pred = np.argmax(model.predict(X_test), axis=1)

    # Calculate confusion matrix and F1 score
    conf_matrix = confusion_matrix(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='weighted')

    print("Round:", _+1)
    print("Confusion Matrix:")
    print(conf_matrix)
    print("F1 Score:", f1)
    print()


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
Round: 1
Confusion Matrix:
[[261   4   4   1]
 [  0  32   0   0]
 [  0   0  55   2]
 [  0   0   0   3]]
F1 Score: 0.971251657487055

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Round: 2
Confusion Matrix:
[[261   3   4   2]
 [  0  32   0   0]
 [  0   0  55   2]
 [  0   0   0   3]]
F1 Score: 0.9719409312999858

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
Round: 3
Confusion Matrix:
[[261   2   4   3]
 [  0  32   0   0]
 [  0   1  55   1]
 [  0   2   0   1]]
F1 Score: 0.9665928518557465

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
Round: 4
Confusion Matrix:
[[261   2   4   3]
 [  0  32   0   0]
 [  0   1  55   1]
 [  0   2   0   1]]
F1 Score: 0.9665928518557465

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 
Round: 5
Confusion Matrix:
[[261   2   4   3]
 [  0  32   0   0]
 [  0   0  55   2]
 [  0   0   0   3]]
F1 Score: 0.9727682862380028

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Round: 6
Confusion Matrix:
[[261   2   4   3]
 [  0  32   0   0]
 [  0   0  55   2]
 [  0   

In [13]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import confusion_matrix, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load data from output.csv
data = pd.read_csv('../output/output.csv')

# Split features and labels
feature_df = data.drop(data.columns[:2], axis=1)
X = np.asarray(feature_df)
y = np.asarray(data['pii_exist'])

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Convert labels to one-hot encoding
num_classes = len(np.unique(y))
y_train_one_hot = tf.one_hot(y_train, depth=num_classes).numpy()
y_test_one_hot = tf.one_hot(y_test, depth=num_classes).numpy()

# Define function to create model
def create_model(num_classes):
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(num_classes, activation='softmax')
    ])
    return model

# Create a list of models representing each client
num_clients = 10
client_models = [create_model(num_classes) for _ in range(num_clients)]

# Define a function for training on each client's data
def train_on_client(X, y, model):
    model.fit(X, y, epochs=10, batch_size=32, verbose=0)
    return model

# Train each client's model
for i, model in enumerate(client_models):
    X_client_train, _, y_client_train, _ = train_test_split(X_train, y_train_one_hot, test_size=0.8, random_state=i)  # Use a portion of the training data for each client
    client_models[i] = train_on_client(X_client_train, y_client_train, model)

# Aggregate weights of all client models to update the global model
global_model = create_model(num_classes)
for model in client_models:
    global_model.set_weights([(w1 + w2) / 2 for w1, w2 in zip(global_model.get_weights(), model.get_weights())])

# Predict classes using the global model
y_pred = np.argmax(global_model.predict(X_test), axis=1)

# Calculate confusion matrix and F1 score
conf_matrix = confusion_matrix(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print("Confusion Matrix:")
print(conf_matrix)
print("F1 Score:", f1)

ValueError: You must call `compile()` before using the model.

In [20]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import confusion_matrix, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load data from output.csv
data = pd.read_csv('../output/output.csv')

# Split features and labels
feature_df = data.drop(data.columns[:2], axis=1)
X = np.asarray(feature_df)
y = np.asarray(data['pii_exist'])

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Convert labels to one-hot encoding
num_classes = len(np.unique(y))
y_train_one_hot = tf.one_hot(y_train, depth=num_classes).numpy()
y_test_one_hot = tf.one_hot(y_test, depth=num_classes).numpy()

# Define function to create model
def create_model(num_classes):
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(num_classes, activation='softmax')
    ])
    return model

# Create a list of models representing each client
num_clients = 10
client_models = [create_model(num_classes) for _ in range(num_clients)]

# Define a function for training on each client's data
def train_on_client(X, y, model):
    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    model.fit(X, y, epochs=10, batch_size=32, verbose=0)
    return model

# Train each client's model
for i, model in enumerate(client_models):
    X_client_train, _, y_client_train, _ = train_test_split(X_train, y_train_one_hot, test_size=0.8, random_state=i)  # Use a portion of the training data for each client
    client_models[i] = train_on_client(X_client_train, y_client_train, model)

# Aggregate weights of all client models to update the global model
global_model = create_model(num_classes)

# Update global model with weights from client models
for model in client_models:
    global_model.set_weights([(w1 + w2) / 2 for w1, w2 in zip(global_model.get_weights(), model.get_weights())])

# Predict classes using the global model
y_pred = np.argmax(global_model.predict(X_test), axis=1)

# Calculate confusion matrix and F1 score
conf_matrix = confusion_matrix(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print("Confusion Matrix:")
print(conf_matrix)
print("F1 Score:", f1)


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step  
Confusion Matrix:
[[71 58 76 65]
 [ 6 14  7  5]
 [46  6  3  2]
 [ 1  1  0  1]]
F1 Score: 0.29793445442583505


In [15]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import confusion_matrix, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load data from output.csv
data = pd.read_csv('../output/output.csv')

# Split features and labels
feature_df = data.drop(data.columns[:2], axis=1)
X = np.asarray(feature_df)
y = np.asarray(data['pii_exist'])

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Convert labels to one-hot encoding
num_classes = len(np.unique(y))
y_train_one_hot = tf.one_hot(y_train, depth=num_classes).numpy()
y_test_one_hot = tf.one_hot(y_test, depth=num_classes).numpy()

# Define function to create model
def create_model(num_classes):
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(num_classes, activation='softmax')
    ])
    return model

# Create a list of models representing each client
num_clients = 10
client_models = [create_model(num_classes) for _ in range(num_clients)]

# Define a function for training on each client's data
def train_on_client(X, y, model):
    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    model.fit(X, y, epochs=10, batch_size=32, verbose=0)
    return model

# Train each client's model
for i, model in enumerate(client_models):
    X_client_train, _, y_client_train, _ = train_test_split(X_train, y_train_one_hot, test_size=0.8, random_state=i)  # Use a portion of the training data for each client
    client_models[i] = train_on_client(X_client_train, y_client_train, model)

# Aggregate weights of all client models to update the global model
global_model = create_model(num_classes)
for model in client_models:
    global_model.set_weights([(w1 + w2) / 2 for w1, w2 in zip(global_model.get_weights(), model.get_weights())])

# Compile the global model
global_model.compile(optimizer='adam',
                     loss='categorical_crossentropy',
                     metrics=['accuracy'])

# Predict classes using the global model
y_pred = np.argmax(global_model.predict(X_test), axis=1)

# Calculate confusion matrix and F1 score
conf_matrix = confusion_matrix(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print("Confusion Matrix:")
print(conf_matrix)
print("F1 Score:", f1)


52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
Confusion Matrix:
[[622 620]
 [280 131]]
F1 Score: 0.4920191137238269


In [25]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import confusion_matrix, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load data from output.csv
data = pd.read_csv('../output/output.csv')

# Split features and labels
feature_df = data.drop(data.columns[:2], axis=1)
X = np.asarray(feature_df)
y = np.asarray(data['pii_exist'])

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Convert labels to one-hot encoding
num_classes = len(np.unique(y))
y_train_one_hot = tf.one_hot(y_train, depth=num_classes).numpy()
y_test_one_hot = tf.one_hot(y_test, depth=num_classes).numpy()

# Define function to create model
def create_model(num_classes):
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(num_classes, activation='softmax')
    ])
    return model

# Create a list of models representing each client
num_clients = 10
client_models = [create_model(num_classes) for _ in range(num_clients)]

# Define a function for training on each client's data
def train_on_client(X, y, model):
    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    model.fit(X, y, epochs=10, batch_size=32, verbose=0)
    return model

# Define privacy parameters
epsilon = 0.1  # Privacy budget

# Train each client's model with differential privacy
for i, model in enumerate(client_models):
    X_client_train, _, y_client_train, _ = train_test_split(X_train, y_train_one_hot, test_size=0.8, random_state=i)
    
    # Train the model with differential privacy
    model = train_on_client(X_client_train, y_client_train, model)
    
    # Add Laplace noise to the gradients
    for layer in model.layers:
        if isinstance(layer, tf.keras.layers.Dense):
            weights = layer.get_weights()
            scale = 1.0 / epsilon
            noisy_weights = [w + np.random.laplace(0, scale, size=w.shape) for w in weights]
            layer.set_weights(noisy_weights)

# Aggregate weights of all client models to update the global model
global_model = create_model(num_classes)
for model in client_models:
    for global_layer, client_layer in zip(global_model.layers, model.layers):
        global_layer_weights = global_layer.get_weights()
        client_layer_weights = client_layer.get_weights()
        new_global_weights = [(gw + cw) / 2 for gw, cw in zip(global_layer_weights, client_layer_weights)]
        global_layer.set_weights(new_global_weights)

# Compile the global model
global_model.compile(optimizer='adam',
                     loss='categorical_crossentropy',
                     metrics=['accuracy'])

# Predict classes using the global model
y_pred = np.argmax(global_model.predict(X_test), axis=1)

# Calculate confusion matrix and F1 score
conf_matrix = confusion_matrix(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print("Confusion Matrix:")
print(conf_matrix)
print("F1 Score:", f1)


52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Confusion Matrix:
[[674 568]
 [170 241]]
F1 Score: 0.5837719571615613


In [14]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import confusion_matrix, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load data from output.csv
data = pd.read_csv('../output/output_binary.csv')

# Split features and labels
feature_df = data.drop(data.columns[:2], axis=1)
X = np.asarray(feature_df)
y = np.asarray(data['pii_exist'])

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Convert labels to one-hot encoding
num_classes = len(np.unique(y))
y_train_one_hot = tf.one_hot(y_train, depth=num_classes).numpy()
y_test_one_hot = tf.one_hot(y_test, depth=num_classes).numpy()

# Define SVM model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_hinge',
              metrics=['accuracy'])

# Define privacy parameters
epsilon = 10 # Privacy budget
sensitivity = 10  # Sensitivity of the gradients

# Define a function for training on each client's data with differential privacy
def train_on_client_dp(X, y, model, epsilon):
    model.compile(optimizer='adam',
                  loss='categorical_hinge',
                  metrics=['accuracy'])
    model.fit(X, y, epochs=10, batch_size=32, verbose=0)

    # Add noise to the gradients
    for layer in model.layers:
        if isinstance(layer, tf.keras.layers.Dense):
            for weight in layer.trainable_variables:
                noise = tf.random.normal(shape=weight.shape, stddev=sensitivity / epsilon)
                weight.assign_add(noise)

    return model

# Federated learning loop with differential privacy
for _ in range(10):  # 10 rounds of federated learning
    # Client 1 trains on its data with differential privacy
    model = train_on_client_dp(X_train, y_train_one_hot, model, epsilon)

    # Client 2 trains on its data with differential privacy
    # model = train_on_client_dp(X_test, y_test_one_hot, model, epsilon)
    y_pred = np.argmax(model.predict(X_test), axis=1)
    f1 = f1_score(y_test, y_pred, average='weighted')
    print("F1 Score:", f1)

# Predict classes
y_pred = np.argmax(model.predict(X_test), axis=1)

# Calculate confusion matrix and F1 score
conf_matrix = confusion_matrix(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print("Confusion Matrix:")
print(conf_matrix)
print("F1 Score:", f1)

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
F1 Score: 0.6107619357823697
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
F1 Score: 0.6074498363201785
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
F1 Score: 0.636959429678451
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
F1 Score: 0.6574585635359116
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 57ms/step
F1 Score: 0.7004663654724179
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
F1 Score: 0.7023285887983823
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
F1 Score: 0.7088687376854633
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
F1 Score: 0.7123829180777758
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
F1 Score: 0.7161069778876137
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
F1 Score: 0.7071823204419889
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
Confusion Matrix:
[[217  53]
 [ 53  39]]
F1 Score: 0.7071823204419889
